<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pedido" nsURI="http://www.eclipse.org/py/sirius/emf/model/pedido"
    nsPrefix="pedido">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Persona" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="validarLetra novaciocorreo"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="validarLetra" value="self.nombre.matches('[A-Z][A-Aa-z]*')"/>
      <details key="novaciocorreo" value="self.correo->notEmpty()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="correo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cliente" eSuperTypes="#//Persona">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="novaciocelular"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="novaciocelular" value="self.celular->notEmpty()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="celular" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Usuario" eSuperTypes="#//Persona">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="novaciopass"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="novaciopass" value="self.password->notEmpty()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pedido">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fechaToma" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fechaEntrega" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="total" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cliente" eType="#//Cliente"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usuario" eType="#//Usuario"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="itempedido" upperBound="-1"
        eType="#//ItemPedido"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItemPedido">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cantidad" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subTotal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="producto" eType="#//Producto"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Producto">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descripcion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fechaVencimiento" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cantidad" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" eType="#//ProductoTipo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Factura">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numero" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pedidos" upperBound="-1"
        eType="#//Pedido" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="producto" upperBound="-1"
        eType="#//Producto" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cliente" upperBound="-1"
        eType="#//Cliente" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usuario" upperBound="-1"
        eType="#//Usuario" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Distribuidora">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cliente" upperBound="-1"
        eType="#//Cliente" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usuario" upperBound="-1"
        eType="#//Usuario" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pedido" upperBound="-1"
        eType="#//Pedido" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="producto" upperBound="-1"
        eType="#//Producto" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="itempedido" upperBound="-1"
        eType="#//ItemPedido" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProductoTipo">
    <eLiterals name="SUPERMERCADO"/>
    <eLiterals name="FARMACIA" value="1"/>
    <eLiterals name="ELECTRONICOS" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NewEnum2"/>
</ecore:EPackage>
